name: Cypress Tests

on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main
  
jobs:
  cypress_tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Update package list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y libxss1 libappindicator3-1 libindicator7

      - name: Download and install Google Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f

      - name: Verify Chrome version
        run: google-chrome --version

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome
