name: Cypress Tests

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run
