name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm Install

      - name: Run Cypress Tests
        run: npx cypress run --headless