name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: windows=latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start